// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxufdcvoupjqvxnwnost.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dWZkY3ZvdXBqcXZ4bndub3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1ODAxODksImV4cCI6MjA2MjE1NjE4OX0.jmr5M3JPqwS1A--2wYD0GH893aGqkdwEzVNOt90FJhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);